// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChnXbVyyeNlylFCCeFM0-_pNq77QS_WK8',
    appId: '1:319076379305:web:c38bec7fe27e53b6ed17b8',
    messagingSenderId: '319076379305',
    projectId: 'rasaye-f99bf',
    authDomain: 'rasaye-f99bf.firebaseapp.com',
    storageBucket: 'rasaye-f99bf.firebasestorage.app',
    measurementId: 'G-SPLBWBFN73',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArCUaNY0YlNygI_KvEBgzVOFiwK-i2IVA',
    appId: '1:319076379305:android:d12ff62bc95cea2ded17b8',
    messagingSenderId: '319076379305',
    projectId: 'rasaye-f99bf',
    storageBucket: 'rasaye-f99bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCobTIz089CVxq3Ppt8kKRKQIe9AZm3qI4',
    appId: '1:319076379305:ios:05d8a1a5629f3ac9ed17b8',
    messagingSenderId: '319076379305',
    projectId: 'rasaye-f99bf',
    storageBucket: 'rasaye-f99bf.firebasestorage.app',
    iosBundleId: 'com.example.zeePalmTasks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCobTIz089CVxq3Ppt8kKRKQIe9AZm3qI4',
    appId: '1:319076379305:ios:05d8a1a5629f3ac9ed17b8',
    messagingSenderId: '319076379305',
    projectId: 'rasaye-f99bf',
    storageBucket: 'rasaye-f99bf.firebasestorage.app',
    iosBundleId: 'com.example.zeePalmTasks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChnXbVyyeNlylFCCeFM0-_pNq77QS_WK8',
    appId: '1:319076379305:web:c1f8e0b9493b1aa4ed17b8',
    messagingSenderId: '319076379305',
    projectId: 'rasaye-f99bf',
    authDomain: 'rasaye-f99bf.firebaseapp.com',
    storageBucket: 'rasaye-f99bf.firebasestorage.app',
    measurementId: 'G-YNV5HPQP4V',
  );
}
